name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.20.0
  - scipy
  - matplotlib
  - pytest
  - flake8
  - pycodestyle
  - isort
  - mypy
  - pylint
  - jupytext
  - pip
  - pip:
    - black
    - pre-commit
    - scipy
    - pytest-mock
    - pytest-env
    - pytest-cov
    - pytest-console-scripts
    - coverage
