name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.20.0
  - scipy
  - matplotlib
  - pytest
  - flake8
  - isort
  - mypy
  - pylint
  - jupytext
  - pip
  - pip:
    - black
    - coverage
    - flake8
    - flake8-bandit
    - flake8-bugbear
    - flake8-comprehensions
    - pre-commit
    - pytest-console-scripts
    - pytest-cov
    - pytest-env
    - pytest-mock
    - scipy
